### ISSUE TITLE
Any movement with the Duo Two-factor App?

### ISSUE THREAD

**Issue by jedunbar** [ChristophWurst/twofactor_duo#1]
Hi, Christoph.

I've been keeping an eye on this repo for a while. Are there any plans to make this a production app any time soon? Our company uses Duo and would really like to integrate it with our Nextcloud 11.0.3 instance. It looks like ownCloud already has an officially signed Duo app: https://apps.owncloud.com/content/show.php/Duo+Two-Factor+Authentication?content=174748

If this isn't the right place to ask this, please let me know. Thanks!

**Comment by ChristophWurst** [comment]
Hi,

I've submitted a PR in the server repo with the patch from the readme. If it gets merged, this and similar apps can be run (again). See https://github.com/nextcloud/server/pull/6250.
