### ISSUE TITLE
Any chance of integrating Duo as a two factor provider? [$400]

### ISSUE THREAD

**Issue by parts223** [ChristophWurst/twofactor_duo#2]
We need to use Duo for 2FA for Nextcloud. I understand that it needs a custom CSP. Is there any possibility that this can be implemented?

**Comment by jedunbar** [comment]
@parts223 

Check out this post. It will give you an idea of the obstacles that are preventing support for the Duo 2FA app for Nextcloud: https://github.com/elie195/duo_provider/issues/10

I stopped using Nextcloud after discussing it with Elie (person that's working on the Duo 2FA app for both ownCloud and Nextcloud) and started using ownCloud 10.0 in its place. It supports Duo pretty well and is constantly updated. Here's another ad-hoc conversation I've been having with Elie regarding name normalization issues with Duo with the ownCloud Duo app: https://github.com/elie195/duo_provider/issues/11#issuecomment-320021563

Hope this helps.

**Comment by ChristophWurst** [comment]
Hi,

you can find the PR for adding the required interface to the nextcloud server here https://github.com/nextcloud/server/pull/6250. I've also updated the app to be compatible with Nextcloud 13.

**Comment by ChristophWurst** [comment]
The patch has been integrated and will be available with Nextcloud 13: https://github.com/nextcloud/server/pull/6250#event-1222512403.
